FROM mcr.microsoft.com/java/jdk:8-zulu-alpine AS birinci
COPY /source /usr/src/uygulama
WORKDIR /usr/src/uygulama
CMD javac uygulama.java

FROM mcr.microsoft.com/java/jdk:8-zulu-alpine 
WORKDIR /uygulama
COPY --from=birinci /usr/src/uygulama .
CMD ["java", "uygulama"]
